# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Rust.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

# Optional: Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
# services:
#   - mysql:latest
#   - redis:latest
#   - postgres:latest

# Optional: Install a C compiler, cmake and git into the container.
# You will often need this when you (or any of your dependencies) depends on C code.
stages:
  - build
  - format
  # - clippy

image: rust:1.67-slim-buster

before_script:
  - rustup toolchain add nightly
  - rustup target add --toolchain nightly thumbv6m-none-eabi
  - rustup component add --toolchain nightly llvm-tools-preview

build:
  stage: build
  script:
    - cargo build

fmt:
  stage: format
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check

# clippy:
#   stage: clippy
#   script:
#     - rustup component add clippy
#     - cargo clippy --all -- -D warnings